### PR TITLE
fix(overlapping): dynamic offset according to username length.

### PR DESCRIPTION
**Pull request by ShashwatAgrawal20**
beautiful :chefs_kiss

- using the `measureText` to measure the username width and setting the offset accordingly.

- idk, but I wasn't able to properly do `npm install` so I removed the `package-lock.json` and installed the dependencies with `npm i --no-cache` and it worked.

### CODE REVIEW

**Review by jindalpriyanshu101 — APPROVED** [review]
Looks fantastic to me!

**Comment by ShashwatAgrawal20** [comment]
@Shobhit-Nagpal should work?

**Comment by ShashwatAgrawal20** [comment]
image

**Comment by Shobhit-Nagpal** [comment]
Perfect. LGTM

**Pull request merged**
